# Handover Manifest — {{CLIENT}} — {{PROTOTYPE_NAME}} v{{VERSION}}

Generated by `ab-handover.sh` — do not edit. Verify with `ab-verify.sh`.

## Engagement
- Client: {{CLIENT}}
- Prototype: {{PROTOTYPE_NAME}}
- Version: {{VERSION}}
- Repo URL: {{REPO_URL}}

## Provenance
| Item | Value |
|---|---|
| Release tag | `ab-prototype-v{{VERSION}}` |
| Release commit SHA | {{RELEASE_SHA}} |
| Handover branch | `handover/v{{VERSION}}` |
| Handover branch SHA | {{HANDOVER_SHA}} |
| Changelog SHA256 | {{CHANGELOG_SHA256}} |
| Artifact file | {{ARTIFACT_NAME}} |
| Artifact SHA256 | {{ARTIFACT_SHA256}} |
| Bundle SHA256 (sidecar) | `{{BUNDLE_NAME}}.sha256` (authoritative — checksum of this archive) |
| Built at (UTC) | {{DATE_UTC}} |
| Builder | {{BUILDER}} |

## Quality gates (verbatim from repo)
```
{{GATE_YAML}}
```

## Contents of this bundle
- `SOURCE/` — git archive of `handover/v{{VERSION}}` (exact handover tree)
- `ARTIFACT/` — release artifact + SHA256SUMS
- `docs/`   — architecture, API, performance, security, compliance, roadmap
- `RELEASE_NOTES.md` — client-facing summary

## Verification
```bash
sha256sum -c {{BUNDLE_NAME}}.sha256
./ab-verify.sh {{BUNDLE_NAME}}.zip
```

## Compliance note
This bundle contains no secrets, real credentials, or personal data by design.
Source code is provided under the engagement's agreed terms (see the signed
MSA / handover addendum).